image:
  repository: ghcr.io/abdelkader-benaissi/k8s-sre-demo
  tag: "0.1.0"
replicas: 3
resources:
  requests: {cpu: 100m, memory: 96Mi}
  limits: {cpu: 500m, memory: 192Mi}
hpa: {minReplicas: 3, maxReplicas: 10, cpu: 60}
postgres:
  image: postgres:17.6-bookworm
redis:
  image: redis:8.2.1-alpine
