name: validate
on:
  pull_request:
  push: {branches: [main]}
permissions: {contents: read}
jobs:
  app:
    runs-on: ubuntu-latest
    defaults: {run: {working-directory: app}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: {go-version: '1.25.x'}
      - run: go test ./...
      - run: go vet ./...
      - run: docker build -t k8s-sre-demo:test .
  chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - run: helm lint deploy/chart
      - run: helm template sre-demo deploy/chart -n sre-lab > /tmp/all.yaml
      - uses: yannh/kubeconform-action@v1
        with: {kubernetes-version: '1.34.0', summary: 'true', strict: 'true', ignore-missing-schemas: 'true', files: '/tmp/all.yaml'}
      - uses: aquasecurity/trivy-action@0.33.1
        with: {scan-type: config, scan-ref: '.', severity: 'HIGH,CRITICAL', exit-code: '1'}
      - run: docker run --rm -v "$PWD:/work" -w /work prom/prometheus:v3.5.0 promtool check rules deploy/chart/files/slo-rules.yml
      - run: docker run --rm -v "$PWD:/work" -w /work prom/prometheus:v3.5.0 promtool test rules observability/rules.test.yml
