name: validate
on:
  pull_request:
  push: {branches: [main]}
permissions: {contents: read}
jobs:
  app:
    runs-on: ubuntu-latest
    defaults: {run: {working-directory: app}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: {go-version: '1.25.x'}
      - run: go test ./...
      - run: go vet ./...
      - run: docker build -t k8s-sre-demo:test .
  chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - uses: actions/setup-go@v5
        with: {go-version: '1.25.x'}
      - run: go install github.com/yannh/kubeconform/cmd/kubeconform@v0.8.0
      - run: helm lint deploy/chart
      - run: helm template sre-demo deploy/chart -n sre-lab > /tmp/all.yaml
      - run: >-
          "$(go env GOPATH)/bin/kubeconform" -kubernetes-version 1.34.0 -summary -strict
          -ignore-missing-schemas /tmp/all.yaml
      - uses: aquasecurity/trivy-action@v0.36.0
        with: {scan-type: config, scan-ref: '.', severity: 'HIGH,CRITICAL', exit-code: '1'}
      - run: docker run --rm -v "$PWD:/work" -w /work prom/prometheus:v3.5.0 promtool check rules deploy/chart/files/slo-rules.yml
      - run: docker run --rm -v "$PWD:/work" -w /work prom/prometheus:v3.5.0 promtool test rules observability/rules.test.yml
